Table styles {
  id int [pk]
  style varchar
  price float
}
Table sizes {
  id int [pk]
  carats decimal
  price float
}
Table metals {
  id int [pk]
  metal varchar
  price float
}
Table order {
  id int [pk]
  styleId int
  sizeId int
  metalId int
  typeId int
  timestamp datetime
}
Table types {
  id int [pk]
  type varchar
  price float
}

Ref: "styles"."id" < "order"."styleId"

Ref: "sizes"."id" < "order"."sizeId"

Ref: "metals"."id" < "order"."metalId"

Ref: "types"."id" < "order"."typeId"